[sources.system_scrape]
type = "host_metrics"
collectors = [ "cgroups", "disk", "memory", "network" ]
namespace = "homer"
scrape_interval_secs = 15

[sources.heplify-server]
type = "prometheus_scrape"
instance_tag = "heplify"
endpoint_tag = "homer"
endpoints = [ "http://heplify-server:9096/metrics" ]
scrape_interval_secs = 15

[sinks.gigapi]
type = "influxdb_metrics"
inputs = [ "heplify-server", "system_scrape" ]
endpoint = "http://gigapi:7971/"
database = "hepstats"
default_namespace = "hepstats"

  [sinks.gigapi.healthcheck]
  enabled = false
