volumes:
    gigapi_data: {}

services:
  gigapi:
    image: ghcr.io/gigapi/gigapi:latest
    container_name: gigapi
    hostname: gigapi
    restart: unless-stopped
    volumes:
      - gigapi_data:/data
    ports:
      - "7971:7971"
    environment:
      - GIGAPI_ROOT=/data
      - GIGAPI_LAYERS_0_NAME=default
      - GIGAPI_LAYERS_0_TYPE=fs
      - GIGAPI_LAYERS_0_URL=file:///data
  
  vector:
    image: timberio/vector:0.31.0-alpine
    container_name: vector
    restart: unless-stopped
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - gigapi
    logging:
      options:
        max-size: "10m"

  hepgen:
    image: qxip/docker-hepgen
    container_name: hepgen
    environment:
    - "HEP_SERVER=heplify-server"
    - "HEP_PORT=9060"
    - "HEP_PROTO=udp4"
    - "LOOP=10"
    restart: unless-stopped
    depends_on:
      - heplify-server
    logging:
      options:
        max-size: "10m"

  hepgen-bad:
    image: qxip/docker-hepgen
    container_name: hepgen-bad
    environment:
    - "HEP_SERVER=heplify-server"
    - "HEP_PORT=9060"
    - "HEP_PROTO=udp4"
    - "LOOP=1"
    - "SLEEP=60"
    - "HEP_CONFIG=b2bcall_rtcp_bad.js"
    restart: unless-stopped
    depends_on:
      - heplify-server
    logging:
      options:
        max-size: "10m"

  heplify-server:
    image: ghcr.io/sipcapture/heplify-server:latest
    container_name: heplify-server
    ports:
      - "9060:9060"
      - "9096:9096"
      - "9060:9060/udp"
      - "9061:9061/tcp"
    command:
      - './heplify-server'
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPTCPADDR=0.0.0.0:9061"
      - "HEPLIFYSERVER_DBSHEMA=mock"
      - "HEPLIFYSERVER_DBDRIVER=mock"
      - "HEPLIFYSERVER_DBADDR="
      - "HEPLIFYSERVER_LOGLVL=info"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
      - "HEPLIFYSERVER_DEDUP=false"
      - "HEPLIFYSERVER_LINEPROTOURL=http://gigapi:7971/write?db=hep"
      - "HEPLIFYSERVER_LINEPROTOIPPORTLABELS=true"
    restart: unless-stopped
    depends_on:
      - gigapi
      - vector
    expose:
      - 9060
      - 9061
      - 9090
      - 9096
    logging:
      options:
        max-size: "50m"

